version: '3.1'

services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 'ian123'
      MYSQL_DATABASE: 'test_db'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  server:
    container_name: node_server
    image: test_server
    restart: always
    environment:
      PORT: 4000
      AUTH_KEY: '3ad12bee5652e3eb6042e911cb7bf7f4'
      MYSQL_PORT: 3306
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: 'test_db'
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'ian123'
    depends_on:
      - db
    ports:
      - 4001:4000
    volumes:
      - ./:/usr/src/app
